[package]
name = "spacetime-bench-module"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = { version = "0.9", default-features = false, features = ["std_rng"] }
spacetimedb = "2.8.0"
serde = { version = "1", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
