name = "drizzle-durable-object-example"
main = "build/worker/shim.mjs"
compatibility_date = "2026-09-01"

[build]
command = "worker-build --release"

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "Counter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Counter"]
