//! SQLite column type builders with documentation.
//!
//! These builders provide documented `const fn` methods that configure column properties.
//! The macro generates code using these builders, giving users hover documentation.
//!
//! # Example (generated by macro)
//!
//! ```rust,ignore
//! const COLUMN: TextBuilder<UsersName> = text::<UsersName>().primary();
//! ```

mod blob;
mod boolean;
mod integer;
mod real;
mod text;

pub use blob::*;
pub use boolean::*;
pub use integer::*;
pub use real::*;
pub use text::*;
