//! Shared context types for table macro generation.
//!
//! This module provides the `ModelType` enum which is used by both SQLite and PostgreSQL
//! table macro implementations to determine which type of model is being generated.

/// Enum representing the different model types generated by the table macros.
///
/// Each table definition generates multiple model structs for different operations:
/// - `Select` - Used for SELECT query results
/// - `PartialSelect` - Used for partial SELECT results (all fields optional)
/// - `Insert` - Used for INSERT operations with builder pattern
/// - `Update` - Used for UPDATE operations with optional fields
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ModelType {
    /// Model for SELECT operations - fields match the original table column types
    Select,
    /// Model for partial SELECT operations - all fields are `Option<T>`
    PartialSelect,
    /// Model for INSERT operations - uses insert value wrappers with marker types
    Insert,
    /// Model for UPDATE operations - all fields are `Option<T>` for partial updates
    Update,
}

impl ModelType {
    /// Returns true if this model type requires all fields to be optional.
    pub(crate) fn requires_optional_fields(&self) -> bool {
        matches!(self, ModelType::PartialSelect | ModelType::Update)
    }

    /// Returns the suffix used for the generated model struct name.
    pub(crate) fn suffix(&self) -> &'static str {
        match self {
            ModelType::Select => "Select",
            ModelType::PartialSelect => "PartialSelect",
            ModelType::Insert => "Insert",
            ModelType::Update => "Update",
        }
    }

    /// Returns a prefix suitable for generating the model struct identifier.
    ///
    /// For example, for a table `Users`:
    /// - `Select` -> `SelectUsers`
    /// - `Insert` -> `InsertUsers`
    pub(crate) fn prefix(&self) -> &'static str {
        match self {
            ModelType::Select => "Select",
            ModelType::PartialSelect => "PartialSelect",
            ModelType::Insert => "Insert",
            ModelType::Update => "Update",
        }
    }
}
