use core::any::Any;

use crate::{SQLParam, SQLSchemaType, SQLTable, TableRef, ToSQL};

/// An index's metadata as associated constants, generated by the index
/// macros.
///
/// Every `DrizzleIndex` also implements [`SQLIndexInfo`].
pub trait DrizzleIndex: Send + Sync + 'static {
    /// Index name.
    const INDEX_NAME: &'static str;

    /// Column names included in this index, in definition order.
    const COLUMN_NAMES: &'static [&'static str];

    /// Whether this is a unique index.
    const IS_UNIQUE: bool = false;

    /// The `WHERE` predicate of a partial index, as SQL text.
    const WHERE_CLAUSE: Option<&'static str> = None;

    /// The table this index belongs to.
    fn table_ref() -> &'static TableRef;
}

// Every `DrizzleIndex` is a `SQLIndexInfo`.
impl<T: DrizzleIndex> SQLIndexInfo for T {
    fn table(&self) -> &'static TableRef {
        T::table_ref()
    }

    fn name(&self) -> &'static str {
        T::INDEX_NAME
    }

    fn columns(&self) -> &'static [&'static str] {
        T::COLUMN_NAMES
    }

    fn is_unique(&self) -> bool {
        T::IS_UNIQUE
    }

    fn where_clause(&self) -> Option<&'static str> {
        T::WHERE_CLAUSE
    }
}

/// Runtime metadata of an index, usable as a trait object.
pub trait SQLIndexInfo: Any + Send + Sync {
    /// The indexed table.
    fn table(&self) -> &'static TableRef;
    /// The index name.
    fn name(&self) -> &'static str;

    /// Column names included in this index, in definition order.
    fn columns(&self) -> &'static [&'static str];

    /// Whether this is a unique index.
    fn is_unique(&self) -> bool {
        false
    }

    /// The `WHERE` predicate of a partial index, as SQL text.
    fn where_clause(&self) -> Option<&'static str> {
        None
    }
}

impl core::fmt::Debug for dyn SQLIndexInfo {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("SQLIndexInfo")
            .field("name", &self.name())
            .field("is_unique", &self.is_unique())
            .field("where_clause", &self.where_clause())
            .field("columns", &self.columns())
            .field("table", &self.table().name)
            .finish()
    }
}

/// An index for the dialect whose value type is `Value`. Renders as its
/// `CREATE INDEX` statement.
///
/// Generated by `#[SQLiteIndex]`, `#[PostgresIndex]` and `#[MySQLIndex]` on a
/// tuple struct listing the columns, such as
/// `struct UserEmailIdx(Users::email);`.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a SQL index for this dialect",
    label = "ensure this type was derived with #[SQLiteIndex], #[PostgresIndex], or #[MySQLIndex]"
)]
pub trait SQLIndex<'a, Type: SQLSchemaType, Value: SQLParam + 'a>:
    SQLIndexInfo + ToSQL<'a, Value>
{
    /// The indexed table.
    type Table: SQLTable<'a, Type, Value>;
}
