use crate::prelude::*;
use crate::{SQL, SQLColumnInfo, SQLParam, SQLSchema, SQLSchemaType, ToSQL};
use core::any::Any;

pub trait SQLModel<'a, V: SQLParam>: ToSQL<'a, V> {
    fn columns(&self) -> Box<[&'static dyn SQLColumnInfo]>;
    fn values(&self) -> SQL<'a, V>;
}

/// Trait for models that support partial selection of fields
pub trait SQLPartial<'a, Value: SQLParam> {
    /// The type representing a partial model where all fields are optional
    /// for selective querying
    type Partial: SQLModel<'a, Value> + Default + 'a;

    fn partial() -> Self::Partial {
        Default::default()
    }
}

pub trait SQLTable<'a, Type: SQLSchemaType, Value: SQLParam + 'a>:
    SQLSchema<'a, Type, Value> + SQLTableInfo + Default + Clone
{
    type Select: SQLModel<'a, Value> + SQLPartial<'a, Value> + Default + 'a;

    /// The type representing a model for INSERT operations on this table.
    /// Uses PhantomData with tuple markers to track which fields are set
    type Insert<T>: SQLModel<'a, Value> + Default;

    /// The type representing a model for UPDATE operations on this table.
    /// This would be generated by the table macro.
    type Update: SQLModel<'a, Value> + Default + 'a;

    /// The aliased version of this table for self-joins and CTEs.
    /// For a table `Users`, this would be `AliasedUsers`.
    type Aliased: SQLTable<'a, Type, Value>;

    /// Creates an aliased version of this table with the given name.
    /// Used for self-joins and CTEs.
    fn alias(name: &'static str) -> Self::Aliased;
}

pub trait SQLTableInfo: Any + Send + Sync {
    fn name(&self) -> &str;
    fn columns(&self) -> Box<[&'static dyn SQLColumnInfo]>;

    /// Returns all tables this table depends on via foreign keys
    fn dependencies(&self) -> Box<[&'static dyn SQLTableInfo]> {
        self.columns()
            .iter()
            .filter_map(|col| col.foreign_key())
            .map(|fk_col| fk_col.table())
            .collect()
    }
}

impl core::fmt::Debug for dyn SQLTableInfo {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("SQLTableInfo")
            .field("name", &self.name())
            .field("columns", &self.columns())
            .finish()
    }
}

pub trait AsTableInfo: Sized + SQLTableInfo {
    fn as_table(&self) -> &dyn SQLTableInfo {
        self
    }
}
