//! Compile-time relation marker traits.

/// Type-level relation marker: `Self` has an outgoing FK to `Target`.
///
/// Generated by table macros for each declared foreign key.
pub trait Relation<Target: ?Sized> {}

/// Compile-time FK join: `Self` has exactly one FK to `Target`.
///
/// Generated by table macros when a single FK exists from `Self` to `Target`.
/// Tables with multiple FKs to the same target must use explicit join conditions.
pub trait Joinable<Target: ?Sized> {
    /// Returns `(self_column, target_column)` pairs for the FK.
    fn fk_columns() -> &'static [(&'static str, &'static str)];
}

/// Marker trait proving that table `T` is part of schema `Self`.
///
/// Generated by schema derive macros and used by compile-time checked builders.
#[diagnostic::on_unimplemented(
    message = "table `{T}` is not part of schema `{Self}`",
    label = "add this table as a field in your schema struct",
    note = "all tables used in queries must be included in the schema"
)]
pub trait SchemaHasTable<T: ?Sized> {}
