//! Compile-time relation marker traits.

/// Type-level relation marker: `Self` has an outgoing FK to `Target`.
///
/// Generated by table macros for each declared foreign key.
pub trait Relation<Target: ?Sized> {}

/// Compile-time FK join: `Self` has exactly one FK to `Target`.
///
/// Generated by table macros when a single FK exists from `Self` to `Target`.
/// Tables with multiple FKs to the same target must use explicit join conditions.
pub trait Joinable<Target: ?Sized> {
    /// Returns `(self_column, target_column)` pairs for the FK.
    fn fk_columns() -> &'static [(&'static str, &'static str)];
}

/// Marker trait proving that table `T` is part of schema `Self`.
///
/// Generated by schema derive macros and used by compile-time checked builders.
pub trait SchemaHasTable<T: ?Sized> {}
