/// A marker trait for types that can be used as SQL parameters.
///
/// This trait is used as a bound on the parameter type in SQL fragments.
/// It ensures type safety when building SQL queries with parameters.
pub trait SQLParam: Clone + std::fmt::Debug {}

// Implement SQLParam for common types
impl SQLParam for String {}
impl SQLParam for &str {}
impl SQLParam for i8 {}
impl SQLParam for i16 {}
impl SQLParam for i32 {}
impl SQLParam for i64 {}
impl SQLParam for isize {}
impl SQLParam for u8 {}
impl SQLParam for u16 {}
impl SQLParam for u32 {}
impl SQLParam for u64 {}
impl SQLParam for usize {}
impl SQLParam for f32 {}
impl SQLParam for f64 {}
impl SQLParam for bool {}
impl<T: SQLParam> SQLParam for Option<T> {}
impl<T: SQLParam> SQLParam for Vec<T> {}
impl<T: SQLParam> SQLParam for &[T] {}
impl<T: SQLParam> SQLParam for &T {}
impl<const N: usize, T: SQLParam> SQLParam for [T; N] {}

pub trait SQLSchema<'a> {
    const NAME: &'a str;
    const TYPE: crate::SQLSchemaType;
    const SQL: &'a str;
}

pub trait SQLColumn: Clone + std::fmt::Debug {
    type Value;
    fn is_primary_key() -> bool;
    fn is_not_null() -> bool;
    fn is_unique() -> bool;
    fn default_value() -> Option<Self::Value>;
    fn default_fn() -> Option<impl Fn() -> Self::Value>;
}

pub trait SQLTable<'a>: SQLSchema<'a> + Clone + std::fmt::Debug {
    /// The type representing a model for SELECT operations on this table.
    /// This would be generated by the table macro.
    type Select;

    /// The type representing a model for INSERT operations on this table.
    /// This would be generated by the table macro.
    type Insert;

    /// The type representing a model for UPDATE operations on this table.
    /// This would be generated by the table macro.
    type Update;
}

/// Marker trait indicating that a table `T` is part of a schema represented by the marker type `S`.
///
/// This trait is used as a bound on methods like `QueryBuilder::from` and `QueryBuilder::join`
/// to ensure that only tables declared within a specific `schema!` macro invocation can be used
/// with the resulting query builder.
///
/// ## Compile-Time Errors
///
/// If you encounter a compile-time error message like:
/// ```text
/// the trait bound `YourTable: querybuilder::core::schema_traits::IsInSchema<...some_marker_module::SchemaMarker>` is not satisfied
/// ```
/// **This almost always means that `YourTable` was not included in the list of tables when the corresponding `schema!` macro was called.**
///
/// For example:
/// ```compile_fail
/// # use querybuilder::prelude::*;
/// # use querybuilder::sqlite::query_builder::{QueryBuilder, SQLiteQueryBuilder};
/// # use procmacros::SQLiteTable;
/// # #[SQLiteTable(name = "users")] struct User { id: i32 };
/// # #[SQLiteTable(name = "posts")] struct Post { id: i32 };
/// // Schema only includes User
/// let qb = querybuilder::schema!([User]);
///
/// // This line will FAIL because Post is not in the schema:
/// let posts = qb.from::<Post>().select_all(); // <-- Error happens here
/// ```
///
/// To fix this, ensure that `YourTable` is listed within the `[...]` of the `schema!` macro call
/// that created the query builder instance you are trying to use.
///
/// Implementations of this trait are generated automatically by the `schema!` macro for each table
/// listed within it, associating those tables with the unique, generated schema marker type `S`.
pub trait IsInSchema<S> {}

// /// Trait for converting a type into a collection of database parameters
// ///
// /// This trait is used by the query builder to convert a struct or other type
// /// into a collection of database parameters.
// pub trait IntoParams<'a, V> {
//     /// Convert this value into a collection of database parameters
//     ///
//     /// Returns a Result with the collection of parameters or an error if
//     /// conversion fails (e.g., during JSON serialization).
//     fn into_params(self) -> ::std::result::Result<Vec<V>, crate::error::DrizzleError>;
// }

// impl<'a, T, P> IntoParams<'a, P> for T
// where
//     T: Clone + Into<P> + SQLParam,
// {
//     fn into_params(self) -> ::std::result::Result<Vec<P>, crate::error::DrizzleError> {
//         Ok(vec![self.into()])
//     }
// }
