//! Shared enum implementation generation for SQLite drivers.
//!
//! This module generates driver-specific enum implementations (turso IntoValue,
//! libsql Into<Value>). The core impls (From<Enum> for SQLiteValue, ToSQL) are
//! now generated by the SQLiteEnum derive macro via DrizzleSQLiteColumn.

use crate::sqlite::field::FieldInfo;
use proc_macro2::TokenStream;
use quote::quote;
use syn::Result;

/// Generate driver-specific enum implementations for a field.
///
/// The core impls (From<Enum> for SQLiteValue, ToSQL) are generated by the
/// SQLiteEnum derive and are NOT duplicated here. This function only generates
/// driver-specific impls that the derive cannot provide.
pub(crate) fn generate_enum_impls_for_field(info: &FieldInfo) -> Result<TokenStream> {
    if !info.is_enum {
        return Ok(quote! {});
    }

    // Generate driver-specific implementations
    // Note: rusqlite FromSql/ToSql are generated by the SQLiteEnum derive directly
    #[cfg(feature = "rusqlite")]
    let rusqlite_impl = super::rusqlite::generate_enum_impls(info)?;
    #[cfg(not(feature = "rusqlite"))]
    let rusqlite_impl = quote! {};

    #[cfg(feature = "turso")]
    let turso_impl = super::turso::generate_enum_impls(info)?;
    #[cfg(not(feature = "turso"))]
    let turso_impl = quote! {};

    #[cfg(feature = "libsql")]
    let libsql_impl = super::libsql::generate_enum_impls(info)?;
    #[cfg(not(feature = "libsql"))]
    let libsql_impl = quote! {};

    Ok(quote! {
        // Driver-specific implementations
        #rusqlite_impl
        #turso_impl
        #libsql_impl
    })
}
