CREATE SCHEMA "auth";
--> statement-breakpoint
CREATE TYPE "auth"."account_status" AS ENUM('active', 'disabled');--> statement-breakpoint
CREATE TABLE "auth"."accounts" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"status" "auth"."account_status" DEFAULT 'active' NOT NULL,
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "auth"."accounts_seq_seq" INCREMENT BY 2 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100 CACHE 1)
);
--> statement-breakpoint
CREATE TABLE "auditLog" (
	"id" serial PRIMARY KEY NOT NULL,
	"userId" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"type" text DEFAULT 'event' NOT NULL,
	"payload" jsonb
);
--> statement-breakpoint
CREATE TABLE "post_tag_votes" (
	"post_id" integer NOT NULL,
	"tag_id" integer NOT NULL,
	"voter_id" integer NOT NULL,
	"value" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "post_tag_votes_pk" PRIMARY KEY("post_id","tag_id","voter_id")
);
--> statement-breakpoint
CREATE TABLE "post_tags" (
	"post_id" integer NOT NULL,
	"tag_id" integer NOT NULL,
	CONSTRAINT "post_tags_post_id_tag_id_pk" PRIMARY KEY("post_id","tag_id")
);
--> statement-breakpoint
CREATE TABLE "posts" (
	"id" serial PRIMARY KEY NOT NULL,
	"author_id" integer NOT NULL,
	"editor_id" integer,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"published_at" timestamp,
	CONSTRAINT "posts_slug_author_unique" UNIQUE NULLS NOT DISTINCT("slug","author_id")
);
--> statement-breakpoint
CREATE TABLE "tags" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "tags_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "name" text DEFAULT 'anon' NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "tags" text[] DEFAULT '{}'::text[] NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "scores" integer[];--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "settings" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "balance" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "rating" double precision;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "level" smallint DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "birthday" date;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "country_code" char(2);--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "last_ip" "inet";--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "updated_at" timestamp;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "external_id" uuid DEFAULT gen_random_uuid() NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "is_active" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "search_name" text GENERATED ALWAYS AS (lower(name)) STORED;--> statement-breakpoint
ALTER TABLE "auth"."accounts" ADD CONSTRAINT "accounts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auditLog" ADD CONSTRAINT "auditLog_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_tag_votes" ADD CONSTRAINT "post_tag_votes_voter_id_users_id_fk" FOREIGN KEY ("voter_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_tag_votes" ADD CONSTRAINT "post_tag_votes_post_id_tag_id_post_tags_post_id_tag_id_fk" FOREIGN KEY ("post_id","tag_id") REFERENCES "public"."post_tags"("post_id","tag_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_tag_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_editor_id_users_id_fk" FOREIGN KEY ("editor_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "posts_published_idx" ON "posts" USING btree ("published_at") WHERE "posts"."published_at" is not null;--> statement-breakpoint
CREATE INDEX "users_name_idx" ON "users" USING btree ("name");--> statement-breakpoint
CREATE INDEX "users_created_idx" ON "users" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "users_external_id_idx" ON "users" USING btree ("external_id");--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "balance_non_negative" CHECK ("users"."balance" >= 0);--> statement-breakpoint
CREATE VIEW "public"."active_users" AS (select "id", "email" from "users" where "users"."is_active" = true);--> statement-breakpoint
CREATE MATERIALIZED VIEW "public"."post_counts" AS (select "author_id", count(*) as "total" from "posts" group by "posts"."author_id");