//! Init command - create a new drizzle.toml configuration file

use colored::Colorize;
use std::path::Path;

pub fn run(dialect: &str) -> anyhow::Result<()> {
    let config_path = Path::new("drizzle.toml");

    if config_path.exists() {
        anyhow::bail!("drizzle.toml already exists. Remove it first if you want to reinitialize.");
    }

    let config_content = match dialect {
        "sqlite" => {
            r#"# Drizzle configuration for SQLite
dialect = "sqlite"
out = "./drizzle"
breakpoints = true

# Schema file path (generated by build.rs or exported)
# schema = "./schema.json"

# Database connection for introspection/push (optional)
# [database]
# url = "sqlite:./dev.db"

# Migrations table configuration (optional)
# [migrations]
# table = "__drizzle_migrations"
"#
        }
        "postgresql" | "postgres" => {
            r#"# Drizzle configuration for PostgreSQL
dialect = "postgresql"
out = "./drizzle"
breakpoints = true

# Schema file path (generated by build.rs or exported)
# schema = "./schema.json"

# Database connection for introspection/push (optional)
# [database]
# url = "postgres://user:password@localhost:5432/db"

# Migrations table configuration (optional)
# [migrations]
# table = "__drizzle_migrations"
# schema = "public"
"#
        }
        "mysql" => {
            r#"# Drizzle configuration for MySQL
dialect = "mysql"
out = "./drizzle"
breakpoints = true

# Schema file path (generated by build.rs or exported)
# schema = "./schema.json"

# Database connection for introspection/push (optional)
# [database]
# url = "mysql://user:password@localhost:3306/db"

# Migrations table configuration (optional)
# [migrations]
# table = "__drizzle_migrations"
"#
        }
        _ => {
            anyhow::bail!("Invalid dialect: {}. Expected: sqlite, postgresql, mysql", dialect);
        }
    };

    std::fs::write(config_path, config_content)?;

    println!("{} Created drizzle.toml", "✓".green().bold());
    println!();
    println!("Next steps:");
    println!("  1. Update drizzle.toml with your schema path");
    println!("  2. Run {} to generate migrations", "drizzle generate".cyan());

    Ok(())
}

