// "drizzle-rs vs SeaORM, Diesel, Toasty". Every snippet was compiled and run
// against the versions in VERSIONS; drizzle snippets are in verify/src/main.rs.
import { Timeline, boot, h, prog, ease, reveal, lerp } from "./engine/engine.js";
import { stage } from "./engine/stage.js";
import { at, header, captions, codeWindow, stagger } from "./engine/kit.js";
import { VERSIONS, TOPICS, SCHEMA_LINES, SAFETY, STRENGTHS } from "./comparison-data.js";

const root = document.getElementById("stage");
const tl = new Timeline(root);
const CH = ["Schema", "Everyday query", "Aggregates", "Nested data", "Compile-time safety", "Verdict"];
const ORMS = ["Diesel", "SeaORM", "Toasty"];

// ─────────────────────────────────────────────────────────────── intro
tl.scene(7, (el, len) => {
  const a = at(el, 0, 300, h("div", { class: "logo", style: { fontSize: "120px", width: "1920px", justifyContent: "center" } }, h("span", {}, "drizzle"), h("span", { class: "rs" }, "-rs")));
  const vs = at(el, 0, 470, h("div", { style: { width: "1920px", display: "flex", justifyContent: "center", gap: "22px", alignItems: "center" } },
    h("span", { class: "sub", style: { fontSize: "40px" } }, "vs"),
    ...ORMS.map((o) => h("span", { class: "pill", style: { fontSize: "34px", padding: "16px 30px" } }, o))));
  const t = at(el, 0, 620, h("div", { class: "headline", style: { width: "1920px", textAlign: "center", fontSize: "56px" }, html: "Same schema. Same questions. <span class=accent>Real compiler output.</span>" }));
  const v = at(el, 0, 730, h("div", { class: "sub mono", style: { width: "1920px", textAlign: "center", fontSize: "22px" } }, VERSIONS.line));
  return (lt) => {
    reveal(a, lt, 0.1, len - 0.5, 0.7, 30);
    stagger([...vs.children], lt, 0.8, 0.18, len - 0.5);
    reveal(t, lt, 1.8, len - 0.5);
    reveal(v, lt, 2.6, len - 0.5);
  };
});

// ─────────────────────────────────────────────────────────────── schema
tl.scene(13, (el, len) => {
  const head = header(el, "01 · Schema", "users → posts → comments. <span class=accent>What do you write?</span>");
  const max = Math.max(...SCHEMA_LINES.map((r) => r.written + (r.generated || 0)));
  const rows = SCHEMA_LINES.map((r, i) => {
    const y = 300 + i * 132;
    const row = at(el, 110, y, h("div", { style: { width: "1700px" } }));
    const label = h("div", { style: { display: "flex", alignItems: "baseline", gap: "18px", marginBottom: "12px" } },
      h("span", { class: "caption", style: { width: "200px", color: r.name === "drizzle-rs" ? "var(--lime)" : "var(--text)" } }, r.name),
      h("span", { class: "sub", style: { fontSize: "22px" }, html: r.note }));
    const track = h("div", { style: { position: "relative", height: "34px" } });
    const w = (n) => (n / max) * 1180;
    const bar = h("div", { style: { position: "absolute", left: 0, top: 0, height: "34px", borderRadius: "8px", background: r.name === "drizzle-rs" ? "var(--lime)" : "#3a4556" } });
    const gen = h("div", { style: { position: "absolute", top: 0, height: "34px", borderRadius: "8px", background: "repeating-linear-gradient(45deg,#232b37 0 8px,#1a2029 8px 16px)" } });
    const num = h("span", { class: "mono", style: { position: "absolute", top: "2px", fontSize: "24px", fontWeight: 700 } });
    track.append(gen, bar, num);
    row.append(label, track);
    return { row, bar, gen, num, r, w };
  });
  const legend = at(el, 110, 860, h("div", { class: "sub", style: { fontSize: "22px" }, html: `Non-blank lines for 3 tables, their relations, and insert/update models. <span style="display:inline-block;width:28px;height:14px;background:repeating-linear-gradient(45deg,#232b37 0 6px,#1a2029 6px 12px);vertical-align:middle;border-radius:3px"></span> = generated by a CLI from the database.` }));
  return (lt) => {
    head(lt, len);
    rows.forEach((o, i) => {
      reveal(o.row, lt, 0.6 + i * 0.25, len - 0.5);
      const p = prog(lt, 1.2 + i * 0.25, 2.8 + i * 0.25, ease.out);
      const wr = o.w(o.r.written) * p, wg = o.w(o.r.generated || 0) * p;
      o.bar.style.width = wr + "px";
      o.gen.style.left = wr + 6 + "px";
      o.gen.style.width = wg + "px";
      o.num.style.left = wr + (wg ? wg + 12 : 0) + 16 + "px";
      o.num.textContent = Math.round(o.r.written * p) + (o.r.generated ? ` + ${Math.round(o.r.generated * p)} generated` : "");
    });
    reveal(legend, lt, 3.2, len - 0.5);
  };
}, { chapter: "Schema" });

// ─────────────────────────────────────────────────────────────── topic scenes
/** drizzle on the left, competitors cycling on the right. */
function topic(t, chapter, n) {
  const per = 4.6, t0 = 2.4;
  const len = t0 + per * 3 + 1.4;
  tl.scene(len, (el) => {
    const head = header(el, `0${n} · ${chapter}`, t.title);
    const q = at(el, 110, 232, h("div", { class: "sub", html: t.question }));
    // largest font (max 20px) at which the snippet fits its window
    const fit = (code, width, height) => {
      const ls = code.replace(/^\n/, "").split("\n");
      const longest = Math.max(...ls.map((l) => l.length));
      return Math.min(23, Math.floor((width - 64) / (longest * 0.61)), Math.floor((height - 56) / (ls.length * 1.55)));
    };
    const H = 420;
    const dz = codeWindow(el, 110, 300, { title: `drizzle-rs · ${t.drizzle.lines} lines`, width: 800, size: fit(t.drizzle.code, 800, H), height: H, states: [{ at: 0, code: t.drizzle.code }] });
    dz.win.querySelector(".title").style.color = "var(--lime)";
    const dzNote = at(el, 110, 800, h("div", { class: "card", style: { width: "800px", fontSize: "23px", lineHeight: 1.45 }, html: t.drizzle.note }));
    const tabs = at(el, 960, 240, h("div", { style: { display: "flex", gap: "10px" } }, ORMS.map((o) => h("span", { class: "pill", style: { fontSize: "20px", padding: "8px 18px" } }, o))));
    const panes = ORMS.map((o, i) => {
      const d = t[o];
      const w = codeWindow(el, 960, 300, { title: `${o} · ${d.lines} lines${d.status ? " · " + d.status : ""}`, width: 850, size: fit(d.code, 850, H), height: H, states: [{ at: 0, code: d.code }] });
      const note = at(el, 960, 800, h("div", { class: "card", style: { width: "850px", fontSize: "23px", lineHeight: 1.45 }, html: d.note }));
      return { w, note, a: t0 + i * per };
    });
    return (lt) => {
      head(lt, len);
      reveal(q, lt, 0.3, len - 0.5);
      reveal(dz.win, lt, 0.5, len - 0.5);
      dz.update(lt);
      reveal(dzNote, lt, 1.0, len - 0.5);
      reveal(tabs, lt, t0 - 0.4, len - 0.5);
      panes.forEach((p, i) => {
        const last = i === panes.length - 1;
        const b = last ? len - 0.5 : p.a + per - 0.35;
        const v = reveal(p.w.win, lt, p.a, b, 0.35, 0);
        p.w.win.style.transform += ` translateX(${(1 - prog(lt, p.a, p.a + 0.35)) * 30}px)`;
        p.w.win.style.display = v > 0 ? "" : "none";
        reveal(p.note, lt, p.a + 0.2, b, 0.35, 10);
        p.w.update(lt);
        const on = lt >= p.a && (last || lt < p.a + per);
        const tab = tabs.children[i];
        tab.style.background = on ? "var(--lime)" : "";
        tab.style.color = on ? "#0b1203" : "";
      });
    };
  }, { chapter });
}
TOPICS.forEach((t, i) => topic(t, CH[i + 1], i + 2));

// ─────────────────────────────────────────────────────────────── safety matrix
tl.scene(24, (el, len) => {
  const head = header(el, "05 · Compile-time safety", "Eight mistakes. <span class=accent>Who catches them before runtime?</span>", { size: 64 });
  const cols = ["drizzle-rs", ...ORMS];
  const X0 = 110, W0 = 640, CW = 265;
  const hdr = cols.map((c, i) => at(el, X0 + W0 + i * CW, 250, h("div", { class: "mono", style: { width: CW - 16 + "px", textAlign: "center", fontSize: "24px", fontWeight: 700, color: i === 0 ? "var(--lime)" : "var(--text)" } }, c)));
  const KIND = { ce: ["compile error", "ok"], rt: ["runtime error", "warn"], silent: ["wrong result", "bad"], panic: ["panic", "bad"], na: ["n/a", ""] };
  const rows = SAFETY.rows.map((r, i) => {
    const y = 290 + i * 66;
    const label = at(el, X0, y, h("div", { style: { width: W0 - 20 + "px", fontSize: "23px", fontWeight: 600, lineHeight: 1.3 }, html: r.label }));
    const cells = cols.map((c, j) => {
      const v = r.cells[j];
      const [txt, cls] = KIND[v.k];
      const cell = h("div", { style: { width: CW - 16 + "px", display: "flex", flexDirection: "column", alignItems: "center", gap: "4px" } },
        h("span", { class: `tag ${cls}`, style: { fontSize: "15px" } }, txt),
        v.d ? h("span", { class: "mono", style: { fontSize: "15px", color: "var(--muted)", textAlign: "center" } }, v.d) : null);
      return at(el, X0 + W0 + j * CW, y, cell);
    });
    return { label, cells, y };
  });
  const totals = at(el, X0, 290 + SAFETY.rows.length * 66 + 6, h("div", { style: { display: "flex", alignItems: "center" } },
    h("div", { class: "caption", style: { width: W0 + "px" } }, "Caught at compile time"),
    ...cols.map((_, i) => {
      // n/a rows don't count against a library
      const cells = SAFETY.rows.map((r) => r.cells[i].k).filter((k) => k !== "na");
      const n = cells.filter((k) => k === "ce").length;
      return h("div", { class: "mono", style: { width: CW + "px", textAlign: "center", fontSize: "40px", fontWeight: 800, color: i === 0 ? "var(--lime)" : "var(--text)" } }, `${n}/${cells.length}`);
    })));
  const caps = captions(el, 110, 912, SAFETY.captions.map(([a, b, html]) => [a, b === "end" ? len : b, html]), { cls: "sub", width: 1700 });
  return (lt) => {
    head(lt, len);
    stagger(hdr, lt, 0.6, 0.1, len - 0.5);
    rows.forEach((r, i) => {
      const a = 1.2 + i * 1.3;
      reveal(r.label, lt, a, len - 0.5, 0.4, 10);
      stagger(r.cells, lt, a + 0.35, 0.12, len - 0.5);
    });
    reveal(totals, lt, 1.2 + rows.length * 1.3 + 0.4, len - 0.5);
    caps(lt);
  };
}, { chapter: "Compile-time safety" });

// ─────────────────────────────────────────────────────────────── fair play
tl.scene(12, (el, len) => {
  const head = header(el, "06 · Verdict", "Credit where it's due.");
  const cards = STRENGTHS.others.map((s, i) => at(el, 110 + i * 580, 300, h("div", { class: "card", style: { width: "550px", minHeight: "340px" }, html:
    `<div class="caption" style="font-size:36px">${s.name}</div><div class="mono" style="color:var(--muted);font-size:18px;margin:6px 0 22px">${s.version}</div>` +
    s.points.map((p) => `<div style="font-size:23px;line-height:1.4;margin-bottom:14px;color:#c9d1dc">${p}</div>`).join("") })));
  return (lt) => { head(lt, len); stagger(cards, lt, 0.6, 0.3, len - 0.5); };
}, { chapter: "Verdict" });

tl.scene(14, (el, len) => {
  const head = header(el, "06 · Verdict", "Where <span class=accent>drizzle-rs</span> fits.");
  const items = STRENGTHS.drizzle.map((p, i) => at(el, 110 + (i % 2) * 860, 300 + Math.floor(i / 2) * 170, h("div", { class: "card", style: { width: "830px", height: "150px" }, html:
    `<div class="caption" style="font-size:30px">${p[0]}</div><div class="sub" style="font-size:22px;margin-top:8px">${p[1]}</div>` })));
  return (lt) => { head(lt, len); stagger(items, lt, 0.6, 0.35, len - 0.5); };
}, { chapter: "Verdict" });

// ─────────────────────────────────────────────────────────────── outro
tl.scene(7, (el, len) => {
  const logo = at(el, 0, 300, h("div", { class: "logo", style: { fontSize: "150px", width: "1920px", justifyContent: "center" } }, h("span", {}, "drizzle"), h("span", { class: "rs" }, "-rs")));
  const cmd = at(el, 0, 530, h("div", { style: { width: "1920px", display: "flex", justifyContent: "center" } },
    h("div", { class: "window term", style: { padding: "26px 40px", font: '500 38px "JetBrains Mono"' }, html: '<span class="prompt">$</span> cargo add drizzle <span class="attr">--features</span> rusqlite' })));
  const url = at(el, 0, 720, h("div", { class: "sub mono", style: { width: "1920px", textAlign: "center", fontSize: "30px" } }, "github.com/themixednuts/drizzle-rs"));
  const fn = at(el, 0, 800, h("div", { class: "sub", style: { width: "1920px", textAlign: "center", fontSize: "20px" } }, VERSIONS.footnote));
  return (lt) => {
    reveal(logo, lt, 0.1, len - 0.7, 0.8, 30);
    reveal(cmd, lt, 0.8, len - 0.7);
    reveal(url, lt, 1.5, len - 0.7);
    reveal(fn, lt, 2.0, len - 0.7);
  };
}, { fadeOut: 0.8 });

stage(tl, root, CH);
boot(tl);
