//! Schema loading and parsing
//!
//! The CLI reads schema from a JSON file that is generated by:
//! 1. A build.rs script that compiles the schema and exports it
//! 2. Direct export from the application using schema.to_snapshot_json()

use crate::error::CliError;
use drizzle_migrations::sqlite::SQLiteSnapshot;
use drizzle_migrations::Dialect;
use std::path::Path;

/// Dialect-agnostic schema holder
#[derive(Debug)]
pub enum Schema {
    Sqlite(SQLiteSnapshot),
    // Postgres(drizzle_migrations::postgres::PostgresSnapshot),
}

impl Schema {
    /// Load schema from a JSON file
    pub fn load(path: &Path, dialect: Dialect) -> Result<Self, CliError> {
        if !path.exists() {
            return Err(CliError::SchemaNotFound(path.display().to_string()));
        }

        let content = std::fs::read_to_string(path)?;

        match dialect {
            Dialect::Sqlite => {
                let snapshot: SQLiteSnapshot = serde_json::from_str(&content)?;
                Ok(Schema::Sqlite(snapshot))
            }
            // Dialect::Postgresql => {
            //     let snapshot: drizzle_migrations::postgres::PostgresSnapshot = serde_json::from_str(&content)?;
            //     Ok(Schema::Postgres(snapshot))
            // }
            _ => Err(CliError::InvalidDialect(dialect.to_string())),
        }
    }

    /// Get the dialect
    #[allow(dead_code)]
    pub fn dialect(&self) -> Dialect {
        match self {
            Schema::Sqlite(_) => Dialect::Sqlite,
            // Schema::Postgres(_) => Dialect::Postgresql,
        }
    }
}
