//! Schema loading and parsing
//!
//! The CLI reads schema from a JSON file that is generated by:
//! 1. A build.rs script that compiles the schema and exports it
//! 2. Direct export from the application using schema.to_snapshot_json()

use crate::error::CliError;
use drizzle_migrations::sqlite::SQLiteSnapshot;
use std::path::Path;

/// Dialect-agnostic schema holder
#[derive(Debug)]
pub enum Schema {
    Sqlite(SQLiteSnapshot),
    // Postgres(drizzle_migrations::postgres::PgSnapshot),
}

impl Schema {
    /// Load schema from a JSON file
    pub fn load(path: &Path, dialect: &str) -> Result<Self, CliError> {
        if !path.exists() {
            return Err(CliError::SchemaNotFound(path.display().to_string()));
        }

        let content = std::fs::read_to_string(path)?;

        match dialect {
            "sqlite" | "turso" | "libsql" => {
                let snapshot: SQLiteSnapshot = serde_json::from_str(&content)?;
                Ok(Schema::Sqlite(snapshot))
            }
            // "postgresql" | "postgres" => {
            //     let snapshot: drizzle_migrations::postgres::PgSnapshot = serde_json::from_str(&content)?;
            //     Ok(Schema::Postgres(snapshot))
            // }
            other => Err(CliError::InvalidDialect(other.to_string())),
        }
    }

    /// Get the dialect string
    pub fn dialect(&self) -> &'static str {
        match self {
            Schema::Sqlite(_) => "sqlite",
            // Schema::Postgres(_) => "postgresql",
        }
    }
}

