//! MySQL-specific index definition metadata.

/// Storage/access method requested by a generated MySQL index.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MySQLIndexMethod {
    BTree,
    Hash,
}

impl MySQLIndexMethod {
    #[must_use]
    pub const fn as_sql(self) -> &'static str {
        match self {
            Self::BTree => "BTREE",
            Self::Hash => "HASH",
        }
    }
}

/// Online-DDL algorithm requested for a generated MySQL index.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MySQLIndexAlgorithm {
    Default,
    Inplace,
    Copy,
}

impl MySQLIndexAlgorithm {
    #[must_use]
    pub const fn as_sql(self) -> &'static str {
        match self {
            Self::Default => "DEFAULT",
            Self::Inplace => "INPLACE",
            Self::Copy => "COPY",
        }
    }
}

/// Metadata-lock policy requested for a generated MySQL index.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MySQLIndexLock {
    Default,
    None,
    Shared,
    Exclusive,
}

impl MySQLIndexLock {
    #[must_use]
    pub const fn as_sql(self) -> &'static str {
        match self {
            Self::Default => "DEFAULT",
            Self::None => "NONE",
            Self::Shared => "SHARED",
            Self::Exclusive => "EXCLUSIVE",
        }
    }
}

/// MySQL-only metadata generated by `#[MySQLIndex]`.
pub trait MySQLIndexMetadata {
    const METHOD: Option<MySQLIndexMethod>;
    const ALGORITHM: Option<MySQLIndexAlgorithm>;
    const LOCK: Option<MySQLIndexLock>;
}
